apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: api
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
        - name: api-pod
          image: api:0.1.0
          ports:
            - containerPort: 8000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-client
  template:
    metadata:
      labels:
        app: mlops-client
    spec:
      containers:
      - name: mlops-client
        image: mlops-client:latest
        ports:
        - containerPort: 8501


---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-server
  labels:
    app: mlops-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: mlops-server
    spec:
      containers:
      - name: mlops-server
        image: mlops-server:0.2.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 15
          periodSeconds: 20


---

# Stable deployment (90% of traffic)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-server-stable
spec:
  replicas: 9
  selector:
    matchLabels:
      app: mlops-server
      version: stable
  template:
    metadata:
      labels:
        app: mlops-server
        version: stable
    spec:
      containers:
        - name: mlops-server
          image: mlops-server:0.1.0

---
# Canary deployment (10% of traffic)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-server-canary
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlops-server
      version: canary
  template:
    metadata:
      labels:
        app: mlops-server
        version: canary
    spec:
      containers:
        - name: mlops-server
          image: mlops-server:0.2.0
