# green-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlops-server-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mlops-server
      version: green
  template:
    metadata:
      labels:
        app: mlops-server
        version: green
    spec:
      containers:
      - name: mlops-server
        image: mlops-server:0.2.0