apiVersion: v1
kind: Pod
metadata:
  name: api-pod-1
  labels:
    app: api
    version: 0.1.0
spec:
  containers:
    - name: api
      image: api:0.1.0
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: api-pod-2
  labels:
    app: api
    version: 0.2.0
spec:
  containers:
    - name: api
      image: api:0.2.0
      ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
  name: api-pod-3
  labels:
    app: api
    version: 0.3.0
spec:
  containers:
    - name: api
      image: api:0.3.0
      ports:
        - containerPort: 8000

apiVersion: v1
kind: Pod
metadata:
  name: mlops-client
  labels:
    app: api
    version: latest
spec:
  containers:
    - name: mlops-client
      image: mlops-client:latest
      ports:
        - containerPort: 8501

---

apiVersion: v1
kind: Pod
metadata:
  name: mlops-server
  labels:
    app: api
    version: 0.2.0
spec:
  containers:
    - name: mlops-server
      image: mlops-server:0.2.0
      imagePullPolicy: Always  # Add this line to ensure latest image is pulled
      ports:
        - containerPort: 8000
        
